package com.heima.data.exception.days21;
/*
 *	RuntimeException
 *	抛出的异常是RuntimeException类或者子类
 *	运行异常的特点：凡是方法内部抛出的异常是运行异常，xxxException，方法的声明上不需要throws语句，调用者也不需要处理
 *	运行一旦发生，必须修改源代码，异常之后的代码没有再执行的意义了
 */
public class RuntimeExceptionDemo {
	public static void main(String[] args) {
		
	}
}
